#!/bin/bash
fulload(){
  echo "Starting fork $1";
  dd if=/dev/zero of=/dev/null | dd if=/dev/zero of=/dev/null | dd if=/dev/zero of=/dev/null | dd if=/dev/zero of=/dev/null &
};
start=1;
if [ "$1" != "" ];then
  for (( i=$start;i<=$1;i++ )); do
    fulload $i;
  done;
else
  fulload 1;
fi;
read;
killall dd;
